-- Table order and constraints rearranged for valid execution.

-- Enable pgcrypto extension for password hashing/verification functions
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. ENUM Types
CREATE TYPE aal_level AS ENUM (
    'aal1',
    'aal2',
    'aal3'
);

CREATE TYPE action AS ENUM (
    'INSERT',
    'UPDATE',
    'DELETE',
    'TRUNCATE',
    'ERROR'
);

CREATE TYPE buckettype AS ENUM (
    'STANDARD',
    'ANALYTICS',
    'VECTOR'
);

CREATE TYPE code_challenge_method AS ENUM (
    's256',
    'plain'
);

CREATE TYPE enable_reminder AS ENUM (
    'yes',
    'no'
);

CREATE TYPE equality_op AS ENUM (
    'eq',
    'neq',
    'lt',
    'lte',
    'gt',
    'gte',
    'in'
);

CREATE TYPE factor_status AS ENUM (
    'unverified',
    'verified'
);

CREATE TYPE factor_type AS ENUM (
    'totp',
    'webauthn',
    'phone'
);

CREATE TYPE oauth_authorization_status AS ENUM (
    'pending',
    'approved',
    'denied',
    'expired'
);

CREATE TYPE oauth_client_type AS ENUM (
    'public',
    'confidential'
);

CREATE TYPE oauth_registration_type AS ENUM (
    'dynamic',
    'manual'
);

CREATE TYPE oauth_response_type AS ENUM (
    'code'
);

CREATE TYPE one_time_token_type AS ENUM (
    'confirmation_token',
    'reauthentication_token',
    'recovery_token',
    'email_change_token_new',
    'email_change_token_current',
    'phone_change_token'
);

CREATE TYPE role AS ENUM (
    'admin',
    'manager',
    'employee',
    'viewer'
);

CREATE TYPE status AS ENUM (
    'pending',
    'in_progress',
    'completed',
    'rejected'
);

CREATE TYPE user_status AS ENUM (
    'active',
    'inactive',
    'on_leave',
    'terminated'
);


-- 2. Tables (ordered by dependency)

create table public.users (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_name text null,
  password text null,
  email_id text null,
  number bigint null,
  user_access text null,
  given_by text null,
  role text null,
  status public.user_status null,
  department text null,
  leave_date timestamp without time zone null,
  remark text null,
  leave_end_date timestamp without time zone null,
  employee_id text null,
  system_access text null,
  page_access text null,
  profile_image text null,
  "Designation" text null,
  reported_by text null,
  can_self_assign boolean null default false,
  constraint users_pkey primary key (id),
  constraint users_employee_id_key unique (employee_id)
) TABLESPACE pg_default;

create table public.notifications (
  id uuid not null default gen_random_uuid (),
  title text not null,
  message text not null,
  role_target text null default 'all'::text,
  created_at timestamp with time zone null default now(),
  created_by smallint null,
  constraint notifications_pkey primary key (id)
) TABLESPACE pg_default;

create table public.user_notifications (
  id uuid not null default gen_random_uuid (),
  user_id bigint null,
  notification_id uuid null,
  is_read boolean null default false,
  created_at timestamp with time zone null default now(),
  constraint user_notifications_pkey primary key (id),
  constraint user_notifications_user_id_notification_id_key unique (user_id, notification_id),
  constraint user_notifications_notification_id_fkey foreign KEY (notification_id) references notifications (id) on delete CASCADE,
  constraint user_notifications_user_id_fkey foreign KEY (user_id) references users (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.ea_tasks (
  task_id serial not null,
  doer_name text not null,
  phone_number text null,
  planned_date timestamp with time zone not null,
  task_description text not null,
  status text null default 'pending'::text,
  given_by text null,
  extended_date timestamp with time zone null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  remarks text null,
  task_start_date timestamp with time zone not null default now(),
  admin_done boolean null,
  duration text null,
  audio_url text null,
  admin_approval_date timestamp with time zone null,
  admin_approved_by text null,
  image_url text null,
  attachment boolean null,
  constraint ea_tasks_pkey primary key (task_id),
  constraint ea_tasks_status_check check (
    (
      status = any (
        array['pending'::text, 'done'::text, 'extended'::text]
      )
    )
  )
) TABLESPACE pg_default;

create table public.ea_tasks_done (
  id serial not null,
  task_id integer null,
  doer_name text null,
  phone_number text null,
  planned_date timestamp with time zone null,
  task_description text null,
  status text null,
  submission_date timestamp with time zone null default now(),
  image_url text null,
  given_by text null,
  task_start_date timestamp with time zone null default now(),
  admin_done boolean null,
  reason text null,
  next_extend_date timestamp with time zone null,
  duration text null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  audio_url text null,
  admin_approval_date timestamp with time zone null,
  admin_approved_by text null,
  attachment boolean null,
  constraint ea_tasks_done_pkey primary key (id),
  constraint ea_tasks_done_task_id_fkey foreign KEY (task_id) references ea_tasks (task_id) on delete set null,
  constraint ea_tasks_done_status_check check (
    (
      status = any (
        array[
          'pending'::text,
          'done'::text,
          'approved'::text,
          'rejected'::text,
          'extended'::text,
          'Pending'::text,
          'Done'::text,
          'Approved'::text,
          'Rejected'::text,
          'Extended'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

create table public.assign_from (
  id bigint generated always as identity not null,
  name text not null,
  created_at timestamp with time zone null default now(),
  constraint assign_from_pkey primary key (id),
  constraint assign_from_name_key unique (name)
) TABLESPACE pg_default;

create table public.checklist (
  task_id bigint generated by default as identity not null,
  department text null,
  given_by text null,
  name text null,
  task_description text null,
  enable_reminder public.enable_reminder null,
  require_attachment public.enable_reminder null,
  frequency text null,
  remark text null,
  status public.enable_reminder null,
  image text null,
  admin_done boolean null default false,
  delay interval null,
  planned_date text null,
  created_at timestamp without time zone null default now(),
  task_start_date timestamp without time zone null,
  submission_date timestamp without time zone null,
  duration text null,
  audio_url text null,
  admin_approval_date timestamp with time zone null,
  admin_approved_by text null,
  instruction_attachment_url text null,
  instruction_attachment_type text null,
  constraint checklist_pkey primary key (task_id)
) TABLESPACE pg_default;

create table public.delegation (
  task_id bigint generated by default as identity not null,
  created_at timestamp without time zone not null default now(),
  department text null,
  name text null,
  task_description text null,
  frequency text null,
  remarks text null,
  task_start_date timestamp without time zone not null,
  given_by text null,
  image text null,
  enable_reminder public.enable_reminder null,
  require_attachment text null,
  status text null,
  updated_at timestamp without time zone null,
  planned_date timestamp without time zone null,
  submission_date timestamp without time zone null,
  color_code_for bigint null,
  delay interval null,
  admin_done boolean null default false,
  duration text null,
  audio_url text null,
  admin_approval_date timestamp with time zone null,
  admin_approved_by text null,
  instruction_attachment_url text null,
  instruction_attachment_type text null,
  constraint delegation_pkey primary key (task_id)
) TABLESPACE pg_default;

create table public.delegation_done (
  task_id bigint null,
  created_at timestamp with time zone not null default now(),
  status text null,
  next_extend_date timestamp without time zone null,
  reason text null,
  image_url text null,
  name text null,
  task_description text null,
  given_by text null,
  id uuid not null default gen_random_uuid (),
  admin_done boolean null,
  duration text null,
  audio_url text null,
  admin_approval_date timestamp with time zone null,
  admin_approved_by text null,
  constraint delegation_done_pkey primary key (id)
) TABLESPACE pg_default;

create table public.departments (
  id bigint generated always as identity not null,
  name text not null,
  created_at timestamp with time zone null default now(),
  given_by text null,
  constraint departments_pkey primary key (id),
  constraint departments_name_key unique (name)
) TABLESPACE pg_default;

create table public.dropdown_options (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  machine_name text null,
  machine_area text null,
  part_name text null,
  priority text null,
  task_priority text null,
  project_type text null,
  task_status text null,
  sound_test text null,
  temperature text null,
  image_url text null,
  constraint dropdown_options_pkey primary key (id)
) TABLESPACE pg_default;

create table public.holidays (
  id bigint generated by default as identity not null,
  holiday_date date not null,
  holiday_name text not null,
  created_at timestamp with time zone null default now(),
  constraint holidays_pkey primary key (id),
  constraint holidays_holiday_date_key unique (holiday_date)
) TABLESPACE pg_default;

create table public.maintenance_tasks (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  department text null,
  given_by text null,
  name text null,
  task_description text null,
  task_start_date timestamp with time zone null,
  freq text null,
  enable_reminders boolean null default false,
  require_attachment text null,
  submission_date timestamp with time zone null,
  delay text null,
  status text null,
  remarks text null,
  uploaded_image_url text null,
  admin_done boolean null default false,
  buddy text null,
  machine_name text null,
  part_name text null,
  part_area text null,
  duration text null,
  planned_date timestamp with time zone null,
  audio_url text null,
  admin_approval_date timestamp with time zone null,
  admin_approved_by text null,
  constraint maintenance_tasks_pkey primary key (id)
) TABLESPACE pg_default;

create table public.repair_tasks (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  filled_by text not null,
  assigned_person text not null,
  machine_name text not null,
  issue_description text not null,
  part_replaced text null,
  status text null default 'Pending'::text,
  submission_date timestamp with time zone null,
  remarks text null,
  bill_amount text null,
  vendor_name text null,
  work_photo_url text null,
  bill_copy_url text null,
  duration text null,
  audio_url text null,
  admin_approval_date timestamp with time zone null,
  admin_approved_by text null,
  attachment boolean null,
  constraint repair_tasks_pkey primary key (id)
) TABLESPACE pg_default;

create table public.working_day_calender (
  working_date date null,
  day text null,
  week_num integer null,
  month integer null,
  id integer generated by default as identity not null,
  constraint working_day_calender_pkey primary key (id)
) TABLESPACE pg_default;


-- 3. Functions
CREATE OR REPLACE FUNCTION public.calculate_delay_if_late()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.submission_date IS NOT NULL 
       AND NEW.planned_date IS NOT NULL 
       AND NEW.submission_date > NEW.planned_date THEN
        NEW.delay = NEW.submission_date - NEW.planned_date;
    END IF;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.calculate_dynamic_delay()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.task_start_date IS NOT NULL AND NEW.submission_date IS NOT NULL THEN
        NEW.delay = NEW.submission_date - NEW.task_start_date;
    END IF;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.create_notification(
    p_title text, 
    p_message text, 
    p_role_target text DEFAULT 'all'::text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
BEGIN
    INSERT INTO notifications (title, message, role_target, created_by)
    VALUES (p_title, p_message, p_role_target, auth.uid());
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_dropdown_values(column_name text)
RETURNS TABLE(option_value text)
LANGUAGE plpgsql
AS $function$
BEGIN
    -- This effectively runs: SELECT DISTINCT column_name FROM dropdown_options
    RETURN QUERY EXECUTE format(
        'SELECT DISTINCT %I::text FROM dropdown_options WHERE %I IS NOT NULL ORDER BY 1', 
        column_name, 
        column_name
    );
END;
$function$;

CREATE OR REPLACE FUNCTION public.hash_password()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
    -- Only hash if it's a new row or the password has changed
    -- and it doesn't look like a hash already (simple check)
    IF TG_OP = 'INSERT' OR (TG_OP = 'UPDATE' AND NEW.password <> OLD.password) THEN
        -- Only hash if the string doesn't start with '$2a$' (a common bcrypt/blowfish prefix)
        IF NEW.password NOT LIKE '$2a$%' THEN
            NEW.password = crypt(NEW.password, gen_salt('bf', 10));
        END IF;
    END IF;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.increment_color_code_for()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.color_code_for IS NULL THEN
        NEW.color_code_for = 1;
    ELSE
        NEW.color_code_for = NEW.color_code_for + 1;
    END IF;
    RETURN NEW;
END;
$function$; 

CREATE OR REPLACE FUNCTION public.manage_planned_date()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.planned_date IS NULL THEN
        NEW.planned_date = NOW();
    END IF;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.secure_login(
    input_username text, 
    input_password text
)
RETURNS TABLE(
    id bigint, 
    user_name text, 
    role text, 
    user_access text, 
    status text, 
    email_id text, 
    number text, 
    employee_id text
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
BEGIN
    RETURN QUERY
    SELECT 
        u.id::BIGINT,
        u.user_name::TEXT, 
        u.role::TEXT,
        u.user_access::TEXT, 
        u.status::TEXT,
        u.email_id::TEXT,
        u.number::TEXT,
        u.employee_id::TEXT
    FROM users u
    WHERE (u.user_name = input_username OR u.email_id = input_username)
        AND u.password = crypt(input_password, u.password);
END;
$function$;

CREATE OR REPLACE FUNCTION public.set_planned_date_correctly()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.planned_date IS NULL THEN
        NEW.planned_date = NEW.task_start_date;
    END IF;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.update_delay_column()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.submission_date IS NOT NULL AND NEW.task_start_date IS NOT NULL THEN
        NEW.delay = NEW.submission_date - NEW.task_start_date;
    END IF;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.update_delay_hhmmss()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.task_start_date IS NOT NULL AND NEW.submission_date IS NOT NULL THEN
        NEW.delay = NEW.submission_date - NEW.task_start_date;
    END IF;
    RETURN NEW;
END;
$function$;


-- 4. Triggers
create trigger calculate_delay_hhmmss_trigger BEFORE INSERT
or
update on checklist for EACH row
execute FUNCTION update_delay_hhmmss ();

create trigger set_delay_column BEFORE INSERT
or
update on delegation for EACH row
execute FUNCTION update_delay_column ();

create trigger trg_increment_color_code BEFORE
update on delegation for EACH row
execute FUNCTION increment_color_code_for ();

create trigger trg_manage_planned_date BEFORE INSERT
or
update on delegation for EACH row
execute FUNCTION manage_planned_date ();

create trigger trg_set_planned_date_correctly BEFORE INSERT on delegation for EACH row
execute FUNCTION set_planned_date_correctly ();

create trigger trigger_calculate_delay_if_late BEFORE INSERT
or
update on delegation for EACH row
execute FUNCTION calculate_delay_if_late ();

create trigger trigger_calculate_dynamic_delay BEFORE INSERT
or
update on delegation for EACH row
execute FUNCTION calculate_dynamic_delay ();

create trigger tr_hash_password BEFORE INSERT
or
update on users for EACH row
execute FUNCTION hash_password ();


-- 5. Policies
-- Profiles bucket policies
CREATE POLICY "Allow Deletes" ON storage.objects FOR DELETE USING (bucket_id = 'profiles'::text);
CREATE POLICY "Allow Updates" ON storage.objects FOR UPDATE USING (bucket_id = 'profiles'::text);
CREATE POLICY "Allow Uploads" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'profiles'::text);
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'profiles'::text);

-- Task-instructions bucket policies
CREATE POLICY "Allow authenticated deletions" ON storage.objects FOR DELETE USING (bucket_id = 'task-instructions'::text);
CREATE POLICY "Allow public delete 1rg8h65_0" ON storage.objects FOR DELETE USING (bucket_id = 'task-instructions'::text);
CREATE POLICY "Allow public delete 1rg8h65_1" ON storage.objects FOR SELECT USING (bucket_id = 'task-instructions'::text);
CREATE POLICY "Allow public uploads 1rg8h65_0" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'task-instructions'::text);
CREATE POLICY "Allow public uploads 1rg8h65_1" ON storage.objects FOR SELECT USING (bucket_id = 'task-instructions'::text);
CREATE POLICY "task-instructions 1rg8h65_0" ON storage.objects FOR SELECT USING (bucket_id = 'task-instructions'::text);
CREATE POLICY "task_instructions_full_access" ON storage.objects FOR ALL USING (bucket_id = 'task-instructions'::text) WITH CHECK (bucket_id = 'task-instructions'::text);

-- Audio-recordings bucket policies
CREATE POLICY "Allow generic select" ON storage.objects FOR SELECT USING (bucket_id = 'audio-recordings'::text);
CREATE POLICY "Allow generic uploads" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'audio-recordings'::text);

-- Parts bucket policies
CREATE POLICY "Allow public delete from parts bucket" ON storage.objects FOR DELETE USING (bucket_id = 'parts'::text);
CREATE POLICY "Allow public insert to parts bucket" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'parts'::text);
CREATE POLICY "Allow public read access to parts bucket" ON storage.objects FOR SELECT USING (bucket_id = 'parts'::text);
CREATE POLICY "Allow public update to parts bucket" ON storage.objects FOR UPDATE USING (bucket_id = 'parts'::text);
CREATE POLICY "Public Access to parts" ON storage.objects FOR SELECT USING (bucket_id = 'parts'::text);
CREATE POLICY "Images only for parts bucket" ON storage.objects FOR INSERT WITH CHECK ((bucket_id = 'parts'::text) AND (storage.extension(name) = ANY (ARRAY['jpg'::text, 'jpeg'::text, 'png'::text, 'webp'::text])));

-- Checklist bucket policies
CREATE POLICY "Public Access Checklist" ON storage.objects FOR SELECT USING (bucket_id = 'checklist'::text);
CREATE POLICY "Public Insert Checklist" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'checklist'::text);

-- EA bucket policies
CREATE POLICY "Public Access EA" ON storage.objects FOR SELECT USING (bucket_id = 'ea'::text);
CREATE POLICY "Public Insert EA" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'ea'::text);

-- Maintenance bucket policies
CREATE POLICY "Public Access Maintenance" ON storage.objects FOR SELECT USING (bucket_id = 'maintenance'::text);
CREATE POLICY "Public Insert Maintenance" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'maintenance'::text);

-- Repair bucket policies
CREATE POLICY "Public Access Repair" ON storage.objects FOR SELECT USING (bucket_id = 'repair'::text);
CREATE POLICY "Public Insert Repair" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'repair'::text);

-- Maintenance tasks policies
CREATE POLICY "Enable all access for authenticated users" ON public.maintenance_tasks FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for maintenance" ON public.maintenance_tasks FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Enable insert for authenticated users" ON public.maintenance_tasks FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable select for authenticated users" ON public.maintenance_tasks FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable update for authenticated users" ON public.maintenance_tasks FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

-- Repair tasks policies
CREATE POLICY "Enable all access for repair_tasks" ON public.repair_tasks FOR ALL TO public USING (true) WITH CHECK (true);

-- Holidays policies
CREATE POLICY "Enable read access for all" ON public.holidays FOR SELECT TO public USING (true);
CREATE POLICY "Enable all actions for holidays" ON public.holidays FOR ALL TO public USING (true) WITH CHECK (true);

-- Working day calendar policies
CREATE POLICY "Enable read access for all" ON public.working_day_calender FOR SELECT TO public USING (true);
CREATE POLICY "Enable all actions for calendar" ON public.working_day_calender FOR ALL TO public USING (true) WITH CHECK (true);

-- Dropdown options policies
CREATE POLICY "Enable all access for everyone" ON public.dropdown_options FOR ALL TO public USING (true) WITH CHECK (true);

-- Users policies
CREATE POLICY "Public Access" ON public.users FOR ALL TO public USING (true) WITH CHECK (true);

-- Checklist policies
CREATE POLICY "Allow read for sheets" ON public.checklist FOR SELECT TO public USING (true);


-- 6. Storage Buckets Setup
-- Create audio-recordings bucket
INSERT INTO storage.buckets (id, name, public, allowed_mime_types)
VALUES ('audio-recordings', 'audio-recordings', true, ARRAY['audio/mpeg', 'audio/webm', 'audio/wav'])
ON CONFLICT (id) DO NOTHING;

-- Create checklist bucket
INSERT INTO storage.buckets (id, name, public, allowed_mime_types)
VALUES ('checklist', 'checklist', true, NULL)
ON CONFLICT (id) DO NOTHING;

-- Create ea bucket
INSERT INTO storage.buckets (id, name, public, allowed_mime_types)
VALUES ('ea', 'ea', true, NULL)
ON CONFLICT (id) DO NOTHING;

-- Create maintenance bucket
INSERT INTO storage.buckets (id, name, public, allowed_mime_types)
VALUES ('maintenance', 'maintenance', true, NULL)
ON CONFLICT (id) DO NOTHING;

-- Create parts bucket
INSERT INTO storage.buckets (id, name, public, allowed_mime_types)
VALUES ('parts', 'parts', true, NULL)
ON CONFLICT (id) DO NOTHING;

-- Create profiles bucket
INSERT INTO storage.buckets (id, name, public, allowed_mime_types)
VALUES ('profiles', 'profiles', true, NULL)
ON CONFLICT (id) DO NOTHING;

-- Create repair bucket
INSERT INTO storage.buckets (id, name, public, allowed_mime_types)
VALUES ('repair', 'repair', true, NULL)
ON CONFLICT (id) DO NOTHING;

-- Create task-instructions bucket
INSERT INTO storage.buckets (id, name, public, allowed_mime_types)
VALUES ('task-instructions', 'task-instructions', true, NULL)
ON CONFLICT (id) DO NOTHING;


-- 7. Data Seed
INSERT INTO public.working_day_calender (working_date, day, week_num, month)
SELECT 
    gs::date AS working_date,
    CASE 
        WHEN EXTRACT(DOW FROM gs)::int = 0 THEN 'रवि'
        WHEN EXTRACT(DOW FROM gs)::int = 1 THEN 'सोम'
        WHEN EXTRACT(DOW FROM gs)::int = 2 THEN 'मंगल'
        WHEN EXTRACT(DOW FROM gs)::int = 3 THEN 'बुध'
        WHEN EXTRACT(DOW FROM gs)::int = 4 THEN 'गुरु'
        WHEN EXTRACT(DOW FROM gs)::int = 5 THEN 'शुक्र'
        WHEN EXTRACT(DOW FROM gs)::int = 6 THEN 'शनि'
    END AS day,
    EXTRACT(WEEK FROM gs)::int AS week_num,
    EXTRACT(MONTH FROM gs)::int AS month
FROM generate_series(
    '2026-04-22'::date,
    '2027-04-22'::date,
    '1 day'
) AS gs;